# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsentiment.proto\x12\x03nlp\" \n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"1\n\x11SentimentResponse\x12\r\n\x05score\x18\x01 \x01(\x02\x12\r\n\x05label\x18\x02 \x01(\t2O\n\x11SentimentAnalysis\x12:\n\x07\x41nalyze\x12\x15.nlp.SentimentRequest\x1a\x16.nlp.SentimentResponse\"\x00\x42\x11Z\x0fnlp-service/nlpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017nlp-service/nlp'
  _globals['_SENTIMENTREQUEST']._serialized_start=24
  _globals['_SENTIMENTREQUEST']._serialized_end=56
  _globals['_SENTIMENTRESPONSE']._serialized_start=58
  _globals['_SENTIMENTRESPONSE']._serialized_end=107
  _globals['_SENTIMENTANALYSIS']._serialized_start=109
  _globals['_SENTIMENTANALYSIS']._serialized_end=188
# @@protoc_insertion_point(module_scope)
