// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: sentiment.proto

package nlp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SentimentAnalysis_Analyze_FullMethodName = "/nlp.SentimentAnalysis/Analyze"
)

// SentimentAnalysisClient is the client API for SentimentAnalysis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentimentAnalysisClient interface {
	Analyze(ctx context.Context, in *SentimentRequest, opts ...grpc.CallOption) (*SentimentResponse, error)
}

type sentimentAnalysisClient struct {
	cc grpc.ClientConnInterface
}

func NewSentimentAnalysisClient(cc grpc.ClientConnInterface) SentimentAnalysisClient {
	return &sentimentAnalysisClient{cc}
}

func (c *sentimentAnalysisClient) Analyze(ctx context.Context, in *SentimentRequest, opts ...grpc.CallOption) (*SentimentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SentimentResponse)
	err := c.cc.Invoke(ctx, SentimentAnalysis_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentimentAnalysisServer is the server API for SentimentAnalysis service.
// All implementations must embed UnimplementedSentimentAnalysisServer
// for forward compatibility.
type SentimentAnalysisServer interface {
	Analyze(context.Context, *SentimentRequest) (*SentimentResponse, error)
	mustEmbedUnimplementedSentimentAnalysisServer()
}

// UnimplementedSentimentAnalysisServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentimentAnalysisServer struct{}

func (UnimplementedSentimentAnalysisServer) Analyze(context.Context, *SentimentRequest) (*SentimentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedSentimentAnalysisServer) mustEmbedUnimplementedSentimentAnalysisServer() {}
func (UnimplementedSentimentAnalysisServer) testEmbeddedByValue()                           {}

// UnsafeSentimentAnalysisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentimentAnalysisServer will
// result in compilation errors.
type UnsafeSentimentAnalysisServer interface {
	mustEmbedUnimplementedSentimentAnalysisServer()
}

func RegisterSentimentAnalysisServer(s grpc.ServiceRegistrar, srv SentimentAnalysisServer) {
	// If the following call pancis, it indicates UnimplementedSentimentAnalysisServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SentimentAnalysis_ServiceDesc, srv)
}

func _SentimentAnalysis_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SentimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentimentAnalysisServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentimentAnalysis_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentimentAnalysisServer).Analyze(ctx, req.(*SentimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SentimentAnalysis_ServiceDesc is the grpc.ServiceDesc for SentimentAnalysis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentimentAnalysis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nlp.SentimentAnalysis",
	HandlerType: (*SentimentAnalysisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _SentimentAnalysis_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sentiment.proto",
}
