// Code generated by MockGen. DO NOT EDIT.
// Source: review-service/clients (interfaces: Client)

// Package mockcl is a generated GoMock package.
package mockcl

import (
	context "context"
	reflect "reflect"
	nlp "review-service/nlp"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockClient) Analyze(arg0 context.Context, arg1 string) (*nlp.SentimentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", arg0, arg1)
	ret0, _ := ret[0].(*nlp.SentimentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockClientMockRecorder) Analyze(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockClient)(nil).Analyze), arg0, arg1)
}
