// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Review struct {
	ID           uuid.UUID `json:"id"`
	ProductID    string    `json:"product_id"`
	NumOfReviews float64   `json:"num_of_reviews"`
}

type ReviewMessage struct {
	ID        uuid.UUID          `json:"id"`
	Review    string             `json:"review"`
	Score     float64            `json:"score"`
	Label     string             `json:"label"`
	ReviewID  uuid.UUID          `json:"review_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt time.Time          `json:"created_at"`
}
