// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateReviewMessage(ctx context.Context, arg CreateReviewMessageParams) (ReviewMessage, error)
	GetReview(ctx context.Context, id uuid.UUID) (Review, error)
	GetReviewMessage(ctx context.Context, id uuid.UUID) (ReviewMessage, error)
	GetReviewMessages(ctx context.Context, id uuid.UUID) (ReviewMessage, error)
	ReviewCount(ctx context.Context, reviewID uuid.UUID) (int64, error)
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error)
	UpdateReviewMessage(ctx context.Context, arg UpdateReviewMessageParams) (ReviewMessage, error)
}

var _ Querier = (*Queries)(nil)
