// Code generated by MockGen. DO NOT EDIT.
// Source: review-service/helpers (interfaces: Helpers)

// Package mockhlp is a generated GoMock package.
package mockhlp

import (
	reflect "reflect"
	helpers "review-service/helpers"

	gomock "github.com/golang/mock/gomock"
)

// MockHelpers is a mock of Helpers interface.
type MockHelpers struct {
	ctrl     *gomock.Controller
	recorder *MockHelpersMockRecorder
}

// MockHelpersMockRecorder is the mock recorder for MockHelpers.
type MockHelpersMockRecorder struct {
	mock *MockHelpers
}

// NewMockHelpers creates a new mock instance.
func NewMockHelpers(ctrl *gomock.Controller) *MockHelpers {
	mock := &MockHelpers{ctrl: ctrl}
	mock.recorder = &MockHelpersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelpers) EXPECT() *MockHelpersMockRecorder {
	return m.recorder
}

// GetAmazonProductDetails mocks base method.
func (m *MockHelpers) GetAmazonProductDetails(arg0, arg1 string) (*helpers.ResponseDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAmazonProductDetails", arg0, arg1)
	ret0, _ := ret[0].(*helpers.ResponseDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAmazonProductDetails indicates an expected call of GetAmazonProductDetails.
func (mr *MockHelpersMockRecorder) GetAmazonProductDetails(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAmazonProductDetails", reflect.TypeOf((*MockHelpers)(nil).GetAmazonProductDetails), arg0, arg1)
}

// GetAmazonProducts mocks base method.
func (m *MockHelpers) GetAmazonProducts(arg0 string) (*helpers.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAmazonProducts", arg0)
	ret0, _ := ret[0].(*helpers.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAmazonProducts indicates an expected call of GetAmazonProducts.
func (mr *MockHelpersMockRecorder) GetAmazonProducts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAmazonProducts", reflect.TypeOf((*MockHelpers)(nil).GetAmazonProducts), arg0)
}
