version: "3.9"
services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mahanta
      - POSTGRES_DB=review_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d review_service"]
      interval: 5s
      timeout: 1s
      retries: 10

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:mahanta@postgres:5432/review_service?sslmode=disable
      - REDIS=redis://localhost:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/wait-for.sh",
        "redis:5672",
        "--",
        "/app/start.sh",
      ]
    command: ["/app/main"]

volumes:
  redis:
    driver: local
